config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :settings, only: [:index]
  resources :clubs do
  	resources :rules do
	end
	resources :schedules do
	end
  end
  root 'clubs#index'
#	get '/clubs/:id/rules/', to: 'rules#index', as: 'rules'
 # get '/clubs/:id/schedule', to: 'clubs#schedule' 
  #get '/clubs/:id/rules', to: 'clubs#rules' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/club.rb
class Club < ApplicationRecord
	belongs_to :owner, class_name: "User", foreign_key: "owner_id"
#	has_many :rules, foreign_key: :owner_id, dependent: :destroy
	has_many :schedules, foreign_key: :owner_id, dependent: :destroy
end

app/models/club_member.rb
class ClubMember < ApplicationRecord
end

app/models/club_rule.rb
class ClubRule < ApplicationRecord
end

app/models/rule.rb
class Rule < ApplicationRecord
	belongs_to :club, foreign_key: :owner_id
	validates :text, length: {minimum: 1, allow_nil: false, message: "To short"}
end

app/models/rule_set.rb
class RuleSet < ApplicationRecord
end

app/models/rule_set_rule.rb
class RuleSetRule < ApplicationRecord
end

app/models/schedule.rb
class Schedule < ApplicationRecord
	enum day: {monday: 0, tuesday: 1, wensday: 2, thursday: 3, friday: 4, saturday: 5, sunday: 6}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
	def index
		@clubs = Club.all;
	end

	def new
		@club = Club.new
	end

	def create
		@club = Club.new(club_params)

		if @club.save
			redirect_to @club
		else
			render 'new'
		end
	end

	def show
		@club = Club.find(params[:id])
		@title = @club.name
	end

	def schedule
		@title = "Schedule" 
		@club = Club.find(params[:id])
	end

	def rules
		@title = "Rules" 
		@club = Club.find(params[:id])
	end

	def destroy
		@club = Club.find(params[:id])
		@club.destroy

		redirect_to club_path
	end

	private
	def club_params
		params.require(:club).permit(:name)
	end
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
	layout "club-nav"
	def create
		@club = Club.find(params[:club_id])
		@rule = @club.rules.create(rule_params)
		redirect_to club_rules_path(@club)
	end

	def index 
		@title = "Rules"
		@club = Club.find(params[:club_id])
	end

	def edit
	end

	def destroy
		@club = Club.find(params[:club_id])
		@rule = @club.rules.find(params[:id]) 

		@rule.destroy
		redirect_to club_rules_path(@club)
	end
	def show
	end

	private
	def rule_params
		params.require(:rule).permit(:owner, :text)
	end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
	layout "club-nav"
	def create
		@club = Club.find(params[:club_id])
		@schedule= @club.schedules.create(schedule_params)
		redirect_to club_schedules_path(@club)
	end
	def index
		@title = "Schedule"
		@club = Club.find(params[:club_id])
	end

	def destroy
		@club = Club.find(params[:club_id])
		@schedule = @club.schedules.find(params[:id]) 

		@schedule.destroy
		redirect_to club_schedules_path(@club)
	end
	private
	def schedule_params
		params[:schedule][:day].downcase!
		params.require(:schedule).permit(:repeat, :day, :start, :end)
	end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def index 
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/helpers/schedule_helper.rb
module ScheduleHelper
	def ScheduleHelper.time(time)
		arr = time.to_a
		min = arr[1].to_s
		if(min.length == 1)
			min += "0"
		end
		return arr[2].to_s + ":" + min
	end
end

app/views/application/_nav_top.html.haml
%div
  = link_to "Home", root_path
  = link_to "Settings", settings_path

app/views/clubs/index.html.haml
%h1 Listing clubs

%table
  %tr
    %th Name
  - @clubs.each do |club|
    %tr
      %td= club.name

app/views/clubs/new.html.haml
%h1 New Club
= form_with scope: :club, url: clubs_path, local: true do |form|
  - if @club.errors.any?
    #error_explanation
      %h2
        = pluralize(@article.errors.count, "error")
        prohibited this club from being created
      %ul
        - @club.errors.full_messages.each do |msg
        %li
          - msg
  %p
    = form.label :name
    %br/
    = form.text_field :name
    %br/
  %p
    = form.submit
= link_to 'Back', clubs_path

app/views/clubs/show.html.erb
<strong>Schedule</strong>
<div class='page-divider'></div>
<%= render @club.schedules %>
<strong>Rules</strong>
<div class='page-divider'></div>
<%= render @club.rules%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mahjong</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= render 'nav_top' %>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/club-nav.html.erb
<html>
	<head>
		<%= csrf_meta_tags %>

		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		<%= stylesheet_link_tag "club-nav" %>
		<title><%= @title %></title>
	</head>
	<body>
		<strong><%= @title %></strong>
		<% if @club.nil? == false %>
		<ul class='nav'>
			<li><%= link_to "Main", club_path(id: @club.id) %></li>
			<li><%= link_to "Schedules", club_schedules_path(club_id: @club.id) %></li>
			<li><%= link_to "Rules", club_rules_path(club_id: @club.id)%></li>
		</ul>
		<% end %>
		<%= yield %>
	</body>
</html>

app/views/rules/_form.html.erb
<%= form_with(model: @club.rules.build, local: true, url: club_rules_path(club_id: @club.id)) do |form| %>
	<p>
		<%= form.label :text %>
		<%= form.text_field :text %>
	</p>
	<p>
		<%= form.submit %>
	</p>
<% end %>

app/views/rules/_rule.html.erb
<table>
	<% @club.rules.each do |rule| %>
		<tr>
		<td><%=rule.text%></td>
		<td><%= link_to "Delete", club_rule_path(club_id: @club.id, id: rule.id), method: :delete %></td>
		</tr>
	<% end %>
</table>

app/views/rules/index.html.erb
<%= render @club.rules %>
<%= render 'rules/form' %>

app/views/schedules/_form.html.erb
<%= form_with(model: @club.schedules.build, local: true, url: club_schedules_path(club_id: @club.id)) do |form| %>
	<p>
		<%= form.label :repeat %>
		<%= form.check_box :repeat %>
	</p>
	<p>
		<%= form.label :day %>
		<%= form.text_field :day %>
	</p>
	<p>
		<%= form.label :start%>
		<%= form.time_field :start %>
	</p>
	<p>
		<%= form.label :end%>
		<%= form.time_field :end %>
	</p>
	<p>
		<%= form.submit %>
	</p>
<% end %>

app/views/schedules/_schedule.html.erb
<table>
	<% @club.schedules.each do |schedule| %>
		<tr>
			<td><%=schedule.day.capitalize%></td>
			<td><%= ScheduleHelper.time(schedule.start) %></td>
			<td><%= ScheduleHelper.time(schedule.end) %></td>
			<td><%= link_to "Delete", club_schedule_path(club_id: @club.id, id: schedule.id), method: :delete %></td>
		</tr>
	<% end %>
</table>

app/views/schedules/index.html.erb
<%= render @club.schedules %>
<%= render 'schedules/form' %>

app/views/settings/index.html.haml
= form_for current_user, url: settings_path do |f|
  = f.label :first_name
  = f.text_field :first_name
  = f.label :last_name
  = f.text_field :last_name
  = f.submit "Save" 
- if Club.find_by(owner: current_user).nil?
  = link_to "Create Club", new_club_path

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>